DROP TABLE IF EXISTS Member;
DROP TABLE if EXISTS url_mapping;

create table Member
(
    id   integer      not null,
    name varchar(255) not null,
    primary key (id)
);

create table url_mapping
(
    id         bigint generated by default as identity,
    origin_url varchar(255),
    req_count  bigint,
    short_url  varchar(255),
    primary key (id)
);

alter table url_mapping add constraint u_origin_url unique (origin_url);